apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-symfonyapp
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: symfonyapp-root
    app.kubernetes.io/application: symfonyapp-root
spec:
  project: default

  source:
    repoURL: https://github.com/arturas-bes/symfonyapp-deployment.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
